#include "myplanetsim/dynamics/dry_hydrostatic_driver.hpp"
#include "myplanetsim/dynamics/dry_hydrostatic_flux.hpp"
#include "myplanetsim/dynamics/dry_hydrostatic_benchmarks.hpp"
#include "myplanetsim/dynamics/dry_hydrostatic_sources.hpp"
#include <algorithm>
#include <limits>
#include <stdexcept>
namespace mps {
DryHydrostaticDriver::DryHydrostaticDriver(ExperimentConfig c):config_(std::move(c)),grid_(config_.grid.cells_per_panel,config_.planet.radius_m),coordinate_({config_.vertical.a_half_pa,config_.vertical.b_half},config_.vertical.minimum_surface_pressure_pa,config_.vertical.maximum_surface_pressure_pa,config_.vertical.minimum_pressure_thickness_pa){if(config_.kind!=ExperimentKind::kDryHydrostatic)throw std::invalid_argument("dry driver requires dry_hydrostatic config");}
DryHydrostaticState DryHydrostaticDriver::initial_state()const{return initialize_dry_hydrostatic_benchmark(config_,grid_,coordinate_);}
DryHydrostaticDerived DryHydrostaticDriver::diagnose(const DryHydrostaticState&s)const{return diagnose_dry_hydrostatic_state(s,coordinate_,config_.planet);}
DryHydrostaticRhs DryHydrostaticDriver::rhs(const DryHydrostaticState&s)const{auto d=diagnose(s);auto C=d.cells,K=d.levels;DryHydrostaticTransportTendency h;h.air_mass.assign(C*K,0);h.momentum.assign(C*K,{});h.potential_temperature_mass.assign(C*K,0);h.tracer_mass.assign(C*K,0);Real dt=std::numeric_limits<Real>::infinity();for(const auto&e:grid_.edges()){auto l=grid_.cell_index(e.left_cell);auto r=grid_.cell_index(e.right_cell);auto basis=edge_tangent_basis(e);for(std::size_t k=0;k<K;++k){auto ln=dry_hydrostatic_offset(l,k,K);auto rn=dry_hydrostatic_offset(r,k,K);DryHydrostaticPrimitive lp{d.air_mass_kg_m2[ln],d.velocity_m_s[ln],d.potential_temperature_k[ln],d.tracer_mixing_ratio[ln],d.temperature_k[ln]},rp{d.air_mass_kg_m2[rn],d.velocity_m_s[rn],d.potential_temperature_k[rn],d.tracer_mixing_ratio[rn],d.temperature_k[rn]};auto f=rusanov_dry_hydrostatic_flux(lp,rp,basis,config_.planet.gas_constant_j_kg_k,config_.planet.heat_capacity_cp_j_kg_k);auto add=[&](std::size_t c,Real sign){auto n=dry_hydrostatic_offset(c,k,K);auto scale=sign*e.length_m/grid_.cells()[c].area_m2;h.air_mass[n]+=scale*f.air_mass_kg_m_s;h.momentum[n]=h.momentum[n]+scale*f.momentum_kg_s2;h.potential_temperature_mass[n]+=scale*f.potential_temperature_mass_k_kg_m_s;h.tracer_mass[n]+=scale*f.tracer_mass_kg_m_s;};add(l,-1);add(r,1);dt=std::min(dt,config_.dry_hydrostatic.cfl*std::min(grid_.cells()[l].area_m2,grid_.cells()[r].area_m2)/(e.length_m*f.maximum_wave_speed_m_s));}}
 auto coupled=couple_dry_hydrostatic_columns(s,d,h,coordinate_.coefficients().b_half,config_.planet.gravity_m_s2,config_.vertical.transport_scheme,config_.vertical.limiter);auto sources=dry_hydrostatic_sources(grid_,d,config_.planet);for(std::size_t n=0;n<C*K;++n)coupled.tendency.momentum[n]=coupled.tendency.momentum[n]+sources.pressure_gradient_kg_m_s2[n]+sources.coriolis_kg_m_s2[n];return {.surface_pressure_pa_s=std::move(coupled.surface_pressure_pa_s),.tendency=std::move(coupled.tendency),.horizontal_stable_time_step_s=dt,.maximum_continuity_residual_pa_s=coupled.maximum_continuity_residual_pa_s};}
void DryHydrostaticDriver::advance(DryHydrostaticState&s,const Real end,const DryHydrostaticObserver&obs,const DryHydrostaticCancel&cancel)const{if(obs)obs(s,diagnose(s));while(s.time_s<end){if(cancel&&cancel())return;auto r=rhs(s);auto dt=std::min({config_.run.time_step_s,r.horizontal_stable_time_step_s,end-s.time_s});if(!(dt>0))throw std::runtime_error("dry driver stable time step is invalid");for(std::size_t c=0;c<s.surface_pressure_pa.size();++c)s.surface_pressure_pa[c]+=dt*r.surface_pressure_pa_s[c];for(std::size_t n=0;n<s.horizontal_momentum_mass_kg_m_s.size();++n){s.horizontal_momentum_mass_kg_m_s[n]=s.horizontal_momentum_mass_kg_m_s[n]+dt*r.tendency.momentum[n];auto c=n/coordinate_.levels();s.horizontal_momentum_mass_kg_m_s[n]=project_tangent(s.horizontal_momentum_mass_kg_m_s[n],grid_.cells()[c].center);s.potential_temperature_mass_k_kg_m2[n]+=dt*r.tendency.potential_temperature_mass[n];s.tracer_mass_kg_m2[n]+=dt*r.tendency.tracer_mass[n];}s.time_s+=dt;++s.step;auto d=diagnose(s);std::vector<Vec3> centres;for(auto&cell:grid_.cells())centres.push_back(cell.center);validate_dry_hydrostatic_state(s,d,centres,config_.vertical.minimum_surface_pressure_pa,config_.vertical.maximum_surface_pressure_pa,config_.vertical.temperature_floor_k);if(obs)obs(s,d);}}
}
